# compounds.py

COMPOUND_LIBRARY = {
    "H2O": "Water",
    "CO2": "Carbon dioxide",
    "NH3": "Ammonia",
    "CH4": "Methane",
    "NaCl": "Sodium chloride",
    "KCl": "Potassium chloride",
    "Na2O": "Sodium oxide",
    "K2O": "Potassium oxide",
    "MgO": "Magnesium oxide",
    "CaO": "Calcium oxide",
    "Al2O3": "Aluminium oxide",
    "SiO2": "Silicon dioxide",
    "TiO2": "Titanium dioxide",
    "Fe2O3": "Iron(III) oxide",
    "Fe3O4": "Iron oxide",
    "CuO": "Copper(II) oxide",
    "ZnO": "Zinc oxide",
    "BaO": "Barium oxide",
    "SrO": "Strontium oxide",
    "CaCO3": "Calcium carbonate",
    "BaCO3": "Barium carbonate",
    "SrCO3": "Strontium carbonate",
    "MgCO3": "Magnesium carbonate",
    "Na2CO3": "Sodium carbonate",
    "K2CO3": "Potassium carbonate",
    "CaCl2": "Calcium chloride",
    "BaCl2": "Barium chloride",
    "MgCl2": "Magnesium chloride",
    "AlCl3": "Aluminium chloride",
    "FeCl3": "Iron(III) chloride",
    "CuCl2": "Copper(II) chloride",
    "ZnCl2": "Zinc chloride",
    "Na2S": "Sodium sulfide",
    "K2S": "Potassium sulfide",
    "FeS": "Iron(II) sulfide",
    "ZnS": "Zinc sulfide",
    "CuS": "Copper(II) sulfide",
    "CdS": "Cadmium sulfide",
    "Na2Te": "Sodium telluride",
    "K2Te": "Potassium telluride",
    "BaTe": "Barium telluride",
    "CaTe": "Calcium telluride",
    "ZnTe": "Zinc telluride",
    "CdTe": "Cadmium telluride",
    "MgTe": "Magnesium telluride",
    "Al2Te3": "Aluminium telluride",
    "Ga2Te3": "Gallium telluride",
    "In2Te3": "Indium telluride",
    "Ag2Te": "Silver telluride",
    "Cu2Te": "Copper(I) telluride",
    "FeTe": "Iron telluride",
    "NiTe": "Nickel telluride",
    "CoTe": "Cobalt telluride",
    "PbTe": "Lead telluride",
    "Bi2Te3": "Bismuth telluride",
    "Sb2Te3": "Antimony telluride",
    "SnTe": "Tin telluride",
    "MnTe": "Manganese telluride",
    "CrTe": "Chromium telluride",
    "MoTe2": "Molybdenum ditelluride",
    "WTe2": "Tungsten ditelluride",
}